-- Consultation draft storage for NMC response wizard
create table if not exists consultation_drafts (
  id bigint generated by default as identity primary key,
  email text not null,
  answers jsonb default '{}'::jsonb,
  current_theme integer default 0,
  current_item integer default 0,
  created_at timestamptz default now(),
  notified boolean default false
);

-- Index for looking up drafts by email
create index if not exists idx_consultation_drafts_email on consultation_drafts (email);

-- Enable RLS
alter table consultation_drafts enable row level security;

-- Allow service role insert/select
create policy "Service role can insert" on consultation_drafts
  for insert to service_role with check (true);

create policy "Service role can select" on consultation_drafts
  for select to service_role using (true);
